GET http://localhost:8080/test/connection
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-04-12T133342.200.json

###

GET http://localhost:8080/test/connection
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-04-12T132819.200.json

###

